on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Check PureScript Docs
    steps:
    - uses: actions/checkout@v2
    - name: Set up PureScript toolchain
      uses: purescript-contrib/setup-purescript@main
    - name: Check PureScript docs
      uses: ./
